### ISSUE TITLE
Explore simple html + css

### ISSUE THREAD

**Issue by spaceshiptrip** [spaceshiptrip/saratorres-portfolio#2]
Certainly! Below is a simple HTML + CSS version of your website, along with steps to deploy it on GitHub Pages.

### **1. Simple HTML + CSS Website**

Here is the complete HTML code that combines the Home, Resume, and Papers sections into a single page:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sara Torres' Portfolio</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#resume">Resume</a></li>
                <li><a href="#papers">Papers</a></li>
            </ul>
        </nav>
    </header>

    <section id="home">
        <h1>Welcome to My Environmental Biology Portfolio</h1>
        <p>
            Hello! I am a college student passionate about Environmental Biology. I am currently seeking an internship opportunity to apply my skills and knowledge in this field.
        </p>
    </section>

    <section id="resume">
        <h1>My Resume</h1>
        <p>
            Here is my professional resume, highlighting my academic achievements, skills, and experiences in Environmental Biology.
        </p>
        <iframe src="assets/resume.pdf" width="100%" height="600px"></iframe>
        <p><a href="assets/resume.pdf" target="_blank" rel="noopener noreferrer">Download Resume</a></p>
    </section>

    <section id="papers">
        <h1>My Research Papers</h1>
        <ul>
            <li>
                <a href="assets/paper1.pdf" target="_blank" rel="noopener noreferrer">Paper Title 1</a>
                <p>A brief description of what this paper is about.</p>
            </li>
            <li>
                <a href="assets/paper2.pdf" target="_blank" rel="noopener noreferrer">Paper Title 2</a>
                <p>A brief description of what this paper is about.</p>
            </li>
        </ul>
    </section>

    <footer>
        <p>&copy; 2024 Sara Torres</p>
    </footer>
</body>
</html>
```

### **2. CSS File (`styles.css`)**

```css
body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 0;
    padding: 0;
}

header {
    background-color: #4CAF50;
    padding: 10px 0;
    text-align: center;
}

header nav ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
}

header nav ul li {
    margin-right: 15px;
}

header nav ul li a {
    color: white;
    text-decoration: none;
}

header nav ul li a:hover {
    text-decoration: underline;
}

section {
    padding: 20px;
    margin: 20px auto;
    max-width: 800px;
}

section h1 {
    color: #333;
}

iframe {
    border: none;
    margin-top: 20px;
}

footer {
    background-color: #f1f1f1;
    text-align: center;
    padding: 10px 0;
    margin-top: 20px;
}
```

### **3. Steps to Deploy on GitHub Pages**

1. **Create a New Repository on GitHub:**
   - Go to GitHub and create a new repository. You can name it something like `my-portfolio`.

2. **Add Your Files:**
   - Clone the repository to your local machine:
     ```bash
     git clone https://github.com/your-username/my-portfolio.git
     ```
   - Copy your `index.html`, `styles.css`, and `assets` folder (which contains your resume and papers) into the cloned repository.

3. **Commit and Push:**
   - Navigate into the directory where you cloned the repository:
     ```bash
     cd my-portfolio
     ```
   - Add, commit, and push your changes:
     ```bash
     git add .
     git commit -m "Initial commit"
     git push origin main
     ```

4. **Enable GitHub Pages:**
   - Go to the "Settings" tab of your repository on GitHub.
   - Scroll down to the "Pages" section.
   - Under "Source," select the branch you want to deploy from (usually `main`).
   - Click "Save."

5. **Access Your Website:**
   - After enabling GitHub Pages, your website will be live at `https://your-username.github.io/my-portfolio`.

### **Conclusion**

This method gives you a simple, easy-to-maintain website without the need for any JavaScript frameworks. It’s lightweight and can be updated easily by just modifying the HTML and CSS files. 

If you decide to move to a more dynamic setup in the future, you can always transition back to using React or another JavaScript framework.
